version: 2.1

executors:
  docker-logged-in:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
  nodejs:
    docker:
      - image: cimg/node:17.5.0
      

workflows:
  general:
    jobs:
      - test-yarn-install
      - test
      - docker-build-and-push

jobs:
  test-yarn-install:
    executor: nodejs
    steps:
      - checkout
      - run: yarn install
# ----------------------------------------------------------------------------------

  test:
    executor: nodejs
    steps:
      - checkout
      - run: yarn test
# ----------------------------------------------------------------------------------

  docker-build-and-push:
    executor: docker-logged-in
    steps:
      - checkout
      - run: sh .circleci/get-npm-package-version.sh ./services/client/package.json
      - run: docker build ./services/client -t "moonpacket/moonbase-client:0.2.0"
      - run: docker push "moonpacket/moonbase-client:0.2.0"
# ----------------------------------------------------------------------------------

