version: 2.1

executors:
  docker-logged-in:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
  nodejs:
    docker:
      - image: cimg/node:17.5.0
      

workflows:
  general:
    jobs:
      - checkout
      - set-package-version-as-env-variable:
          requires:
            - checkout
      - test:
          requires:
            - checkout
      - docker-build-and-push:
          requires:
            - set-package-version-as-env-variable

jobs:
  checkout:
    executor: nodejs
    steps:
      - checkout
      - run: yarn install
# ----------------------------------------------------------------------------------

  set-package-version-as-env-variable:
    executor: nodejs
    steps:
      - run: sh .circleci/get-npm-package-version.sh ./services/client/package.json
# ----------------------------------------------------------------------------------

  test:
    executor: nodejs
    steps:
      - run: yarn test
# ----------------------------------------------------------------------------------

  docker-build-and-push:
    executor: docker-logged-in
    steps:
      - run: docker build ./services/client -t "moonpacket/moonbase-client:${PACKAGE_VERSION}"
      - run: docker push "moonpacket/moonbase-client:${PACKAGE_VERSION}"
# ----------------------------------------------------------------------------------

